// These are the places the guide can go to.  The first element is the
// word the player must say, the second is the file name of the location
// and the third is what the guide describes the place as.

string *guilds = ({
  "fish",
    "/d/am/cockbill/cockbill8", 
      "the Temple of Fish",
  "small gods",
    "/d/guilds/priests/Ankh-Morpork/small-gods/entrance", 
      "the Temple of the Small Gods",
  "warrior", 
    "/d/am/hero/lobby", 
      "the Warriors' Guild",
  "wizard", 
    "/d/am/square/ss13", 
      "the Unseen University",
  "university", 
    "/d/am/square/ss13", 
      "the Unseen University",
  "assassin", 
    "/d/guilds/assassins/Ankh-Morpork/admin/foyer", 
      "the Assassins' Guild",
  "thief",
    "/d/guilds/thieves/Ankh-Morpork/rooms/ground/entrance",
      "the Thieves' Guild",
  "thieves",
    "/d/guilds/thieves/Ankh-Morpork/rooms/ground/entrance",
      "the Thieves' Guild",
  "gennie",
    "/d/guilds/witches/Ankh-Morpork/gennies_cottage",
      "Gennie's place"});

string *services = ({
  "drum",
    "/d/am/am/mendeddrum",
      "the Mended Drum",
  "bank",
    "/d/am/broad_way/bing_bank",
      "the Bank of Bing",
  "post",
    "/d/am/ampost/foyer",
      "the Post Office",
   "sator stall",
     "/d/guilds/merchants/stalls/am/sator",
     "the Sator Square player stall",
   "cockbill stall",
     "/d/guilds/merchants/stalls/am/cockbill",
      "the Cockbill Street player stall",
  "patrician",
    "/d/am/patrician/foyer",
      "the Patrician's Palace"});

string *places = ({
  "sator square",
    "/d/am/square/ss33", 
      "Sator Square",
  "least gate", 
    "/d/am/gates/least", 
      "the Least Gate",
  "brass bridge",
    "/d/am/river/bridge",
      "the Brass Bridge",
  "widdershins gate",
    "/d/am/gates/widdershins",
      "the Widdenshins Gate",
  "cockbill",
    "/d/am/cockbill/cockbill1",
      "Cockbill Street",
  "plaza",
    "/d/am/plaza/plaza_33",
      "the Plaza of Broken Moons",
  "hubward",
    "/d/am/gates/hubwards",
      "the Hubwards Gate",
  "pillory",
    "/d/am/pillory/pillory2",
      "Pillory Place",
  "ninth yard",
    "/d/am/ninth/ninth1",
      "Ninth Yard"});

