#define M_TIME 0
#define M_FROM 1
#define M_TO 2
#define M_SUB 3
#define M_CC 4
#define M_BODY 5
#define MAIL_TRACK "/obj/handlers/mail_track"
#define MAILER "/obj/handlers/mailer"
#define OUT_MAIL "/net/daemon/out_mail"
#define POST_FROG "/obj/monster/post_frog"
#define FROG_HOME "/d/am/am/post"
