#define ROOM "/d/am/am/"
#define CITYROOM "/d/am/am/cityroom"
#define CHAR ROOM+"chars/"
#define FGUILD "/d/am/fighters/"
#define POST_OFFICE "/d/am/am/post"
#define ITEM "/d/am/am/items/"
#define SHORT "/d/am/am/"
